name: Add Labels

on:
  issues:
    types:
      - opened
      - edited
  issue_comment:
    types:
      - created
      - edited

jobs:
  add-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Check for "BUG" in Issue/PR title
        id: check_bug_label
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.LABEL_GREETING_SECRETS }}
          script: |
            const title = context.payload.issue.title;
            const isBug = title.includes("BUG");
            console.log(`Title: ${title}`);
            console.log(`Is Bug: ${isBug}`);
            return { isBug: isBug }

      - name: Check for "Technology" or "Technology Request" in Issue/PR title or comments
        id: check_technology_label
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.LABEL_GREETING_SECRETS }}
          script: |
            const title = context.payload.issue.title;
            const body = context.payload.issue.body;
            const comments = context.payload.issue.comments;
            const isTechnology = title.includes("Technology") || body.includes("Technology");
            const isTechnologyRequest = title.includes("Technology Request") || body.includes("Technology Request");
            console.log(`Title: ${title}`);
            console.log(`Is Technology: ${isTechnology}`);
            console.log(`Is Technology Request: ${isTechnologyRequest}`);
            return { isTechnology: isTechnology, isTechnologyRequest: isTechnologyRequest }

      - name: Add labels based on conditions
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.LABEL_GREETING_SECRETS }}
          script: |
            const isBug = context.payload.results.check_bug_label.isBug;
            const isTechnology = context.payload.results.check_technology_label.isTechnology;
            const isTechnologyRequest = context.payload.results.check_technology_label.isTechnologyRequest;
            const labelsToAdd = [];

            async function addLabelIfExists(labelName) {
              const { data: labels } = await github.issues.listLabelsForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              
              const label = labels.find(l => l.name === labelName);
              if (label) {
                labelsToAdd.push(label.name);
              }
            }

            if (isBug) {
              await addLabelIfExists("bug");
            }
            if (isTechnology) {
              await addLabelIfExists("Technology");
            }
            if (isTechnologyRequest) {
              await addLabelIfExists("Technology Request");
            }

            console.log(`Labels to add: ${labelsToAdd}`);

            await github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: labelsToAdd
            });
