name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number'
        required: true
      release_date:
        description: 'Release Date'
        required: true
      release_notes:
        description: 'Release Notes'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Environment Variables
        run: |
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          echo "RELEASE_DATE=${{ github.event.inputs.release_date }}" >> $GITHUB_ENV
          echo "RELEASE_NOTES=${{ github.event.inputs.release_notes }}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: npm ci

      - name: Generate .tar.gz
        run: |
          npm run build
          npm pack
          mv dv-social-share-*.tgz dv-social-share-${{ github.event.inputs.version }}.tar.gz

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          body: |
            Version: ${{ github.event.inputs.version }}
            Date: ${{ github.event.inputs.release_date }}
            Release Notes:
            ${{ github.event.inputs.release_notes }}

      - name: Upload .tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: dv-social-share
          path: dv-social-share-${{ github.event.inputs.version }}.tar.gz
