name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
      release_date:
        description: 'Release date'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Nodejs Version
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Set up Environment Variables
        run: |
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          echo "RELEASE_DATE=${{ github.event.inputs.release_date }}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: npm ci

      - name: Generate .tar.gz
        run: |
          npm run build
          npm pack

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          body: |
            Version: ${{ github.event.inputs.version }}
            Date: ${{ github.event.inputs.release_date }}

      - name: Upload .tar.gz
        uses: actions/upload-artifact@v3
        with:
          name: dv-social-share
          path: dv-social-share-${{ github.event.inputs.version }}.tar.gz
